# Add a product
PUT http://localhost:5000/products
Content-Type: application/json

{
    "name": "Ração",
    "code": "555000",
    "amount": 5,
    "description": "Ração Premier"
}

###

# Get all products
GET http://localhost:5000/products

### 

# Update amount
#PATCH  http://localhost:5000/products/id
#Content-Type: application/json

#{
#    "amount": 10 
#}